import type { FC, PropsWithChildren } from "react";
import Head from "next/head";
import { CustomCursor } from "@component/components/CustomCursor";
import { useTheme } from "next-themes";
import { Header } from "@component/components/Header";

export const Main: FC<PropsWithChildren> = ({ children }) => {
  const { theme } = useTheme();

  return (
    <>
      <Head>
        <title>Samed Polat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex h-screen w-screen items-center justify-center p-4">
        <div className="solid relative flex h-full w-full items-center justify-center border">
          <CustomCursor />
          <Header theme={theme} />
          {children}
        </div>
      </main>
    </>
  );
};
