import type { FC, PropsWithChildren } from "react";
import Head from "next/head";
import { CustomCursor } from "@component/components/CustomCursor";
import { useTheme } from "next-themes";
import { Header } from "@component/components/Header";
import { Sphere } from "@component/components/Sphere";
import { Frame } from "@component/components/Frame";
import { ThemeToggle } from "@component/components/ThemeToggle";

export const Main: FC<PropsWithChildren> = ({ children }) => {
  const { theme } = useTheme();

  return (
    <>
      <Head>
        <title>Samed Polat</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex h-screen w-screen items-center justify-center p-8">
        <Frame />
        <CustomCursor />
        {/* <Sphere theme={theme} /> */}
        <div className="solid relative z-[10] grid h-full w-full grid-cols-2 border border-stone-800 p-4 dark:border-stone-300">
          <ThemeToggle />
          <Header theme={theme} />
          <section>{children}</section>
        </div>
      </main>
    </>
  );
};
